name: Kodi
on:
  # Run action when pushed to master, or for commits in a pull request.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  kodi-addon-checker:
    name: Addon checker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kodi-version: [ leia, matrix ]
    steps:
      - name: Check out ${{ github.sha }} from repository ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Run kodi-addon-checker
        uses: xbmc/action-kodi-addon-checker@v1.2
        with:
          kodi-version: ${{ matrix.kodi-version }}
          rewrite-for-matrix: true
          addon-id: ${{ github.event.repository.name }}